/**
 * THE FIRM-OBLIGATIONS SEED CATALOG — SPEC §7's template rows, cell by cell.
 *
 * GENERATED BY `scripts/generate-firm-obligation-catalog.mjs` — DO NOT EDIT BY HAND.
 * Every string below was read out of `docs/specs/firm-obligations-module-spec.md`
 * §7 by program and written through unchanged. The slice carries each row's
 * cite-and-status string "copied, never reworded" (build slice §3 item 3),
 * pinned by "a drift test over a generated constant, the `D-63` shape" (§7
 * item 18), and bars rewording any SPEC §7 cite string (§8). Correct the spec in
 * the design space and re-run the generator;
 * `src/domain/__tests__/firmObligationTemplates.test.ts` re-reads the spec and
 * fails the suite rather than let a divergence reach the register.
 *
 * Nothing here is interpreted. What a row MEANS — its kind, its date hint, its
 * lapse flag, its suggested mark — is built over these cells in
 * `./firmObligationTemplates`, each with the ruling behind it.
 */

/** `FOT-n` in spec order, and `boi-note` for the one "—" row the slice carries. */
export type FirmObligationCatalogKey =
  | "FOT-1"
  | "FOT-2"
  | "FOT-3"
  | "FOT-4"
  | "FOT-5"
  | "FOT-6"
  | "FOT-7"
  | "FOT-8"
  | "FOT-9"
  | "FOT-10"
  | "FOT-11"
  | "FOT-12"
  | "FOT-13"
  | "FOT-14"
  | "FOT-15"
  | "FOT-16"
  | "FOT-17"
  | "FOT-18"
  | "boi-note"
  | "FOT-19"
  | "FOT-20"
  | "FOT-21"
  | "FOT-22"
  | "FOT-23"
  | "FOT-24"
  | "FOT-25"
  | "FOT-26"
  | "FOT-27"
  | "FOT-28"
  | "FOT-29"
  | "FOT-30"
  | "FOT-31"
  | "FOT-32"
  | "FOT-33"
  | "FOT-34"
  | "FOT-35";

/** The `### 7.x` table a row sits in. */
export type FirmObligationCatalogSection =
  | "7.1"
  | "7.2"
  | "7.3"
  | "7.4"
  | "7.5"
  | "7.6"
  | "7.7";

/** Every column header §7's tables use, in first-seen order. */
export type FirmObligationCatalogHeader =
  | "#"
  | "Template"
  | "Kind / anchor"
  | "Lead"
  | "Weight"
  | "Source"
  | "Status"
  | "Conditional on"
  | "Note"
  | "Status / note";

export interface FirmObligationCatalogRow {
  readonly key: FirmObligationCatalogKey;
  readonly section: FirmObligationCatalogSection;
  /** Header → cell, in the table's own column order; each cell VERBATIM, its
   *  table padding trimmed. A header absent from the row's table is absent here. */
  readonly cells: Readonly<Partial<Record<FirmObligationCatalogHeader, string>>>;
}

export const FIRM_OBLIGATION_CATALOG_ROWS: readonly FirmObligationCatalogRow[] = [
  {
    key: "FOT-1",
    section: "7.1",
    cells: {
      "#": "`FOT-1`",
      "Template": "**State Bar membership fee** (annual dues) — **with the $65 legal services fee as a NOTE on the same row** — it is assessed annually on each active member (§ 81.054(j)); whether it is billed with the dues is HIS FACT",
      "Kind / anchor": "`anniversary` — the due date on his dues statement (the statute leaves the date to bar rule, § 81.054(e)–(f)); `precision: month` until the statement arrives; period label his membership year (*\"2026–27\"*)",
      "Lead": "45 d",
      "Weight": "hard",
      "Source": "Tex. Gov't Code § 81.054(a), (e)–(k) — official corpus 2026-08-14 (the (g)/(h) late-renewal multipliers and the (i) 30-day expiration notice are quoted in the record)",
      "Status": "UNVERIFIED; the due date itself is in the State Bar Rules — **NOT HELD**",
      "Conditional on": "—",
    },
  },
  {
    key: "FOT-2",
    section: "7.1",
    cells: {
      "#": "`FOT-2`",
      "Template": "**MCLE compliance**",
      "Kind / anchor": "`anniversary` — the end of his MCLE compliance year (his MCLE record)",
      "Lead": "90 d (a hands-on lead; may want more)",
      "Weight": "hard",
      "Source": "Tex. Gov't Code § 81.113(b)–(c) (participation *\"to the extent required by the supreme court to maintain the person’s state bar membership\"*; an ethics/professional-responsibility component is presupposed by (b)); the hours, the size of the ethics component and the compliance month are in the State Bar Rules / MCLE Regulations",
      "Status": "UNVERIFIED (statute) + **NOT HELD** (rules)",
      "Conditional on": "—",
    },
  },
  {
    key: "FOT-3",
    section: "7.1",
    cells: {
      "#": "`FOT-3`",
      "Template": "**Guardianship certification** (the State Bar course; four hours incl. one on alternatives to guardianship) — the certificate **expires on the second anniversary** of issuance, or the **fourth** for a renewal after four consecutive certified years; an expired certificate ends eligibility for appointment",
      "Kind / anchor": "`anniversary` — the certificate's issue date, `everyYears: 2` (4 once the (b) condition holds)",
      "Lead": "60 d",
      "Weight": "hard",
      "Source": "Tex. Estates Code §§ 1054.201(a)–(b), 1054.202(a)–(b), 1054.203; the course itself, Tex. Gov't Code § 81.114(a) — official corpus 2026-08-14",
      "Status": "UNVERIFIED",
      "Conditional on": "he represents interests in guardianship proceedings or takes guardianship ad litem appointments — HIS FACT",
    },
  },
  {
    key: "FOT-4",
    section: "7.2",
    cells: {
      "#": "`FOT-4`",
      "Template": "**TIDC Attorney Practice Time Report** — ONE obligation, with a per-county checklist in the note (the statute's duty runs *\"to the county\"* for each county in which appointments were accepted; how many submissions that is in practice is TIDC's form's to say) — on TIDC's form, for *\"the preceding fiscal year\"* (which fiscal year is the form's to say; Gov't Code § 79.036(a-1) pairs it with the county's own November 1 report for the preceding fiscal year)",
      "Kind / anchor": "`fixed-annual` — **October 15**",
      "Lead": "30 d (a hands-on lead)",
      "Weight": "hard",
      "Source": "Tex. Code Crim. Proc. art. 26.04(j)(4) — official corpus 2026-08-14 (verbatim in the record); corroborated by Tex. Gov't Code § 79.036(a-1)",
      "Status": "UNVERIFIED",
      "Conditional on": "— (which counties: HIS FACT)",
    },
  },
  {
    key: "FOT-5",
    section: "7.2",
    cells: {
      "#": "`FOT-5`",
      "Template": "**Appointment-list eligibility — whatever the county's indigent-defense plan requires annually** (CLE hours in criminal law, a re-application)",
      "Kind / anchor": "`anniversary` — per the plan",
      "Lead": "60 d",
      "Weight": "hard",
      "Source": "the county's indigent-defense plan — a PUBLIC document (TIDC publishes county plans), **not a named SOURCING channel; not read**; which counties' lists he is on is HIS TO STATE",
      "Status": "NOT READ (plan) / HIS TO STATE (counties)",
      "Conditional on": "per county",
    },
  },
  {
    key: "FOT-6",
    section: "7.3",
    cells: {
      "#": "`FOT-6`",
      "Template": "**Trust-account reconciliation**",
      "Kind / anchor": "`fixed-monthly` — a day he picks; `collapse`",
      "Lead": "5 d",
      "Weight": "**hard** — his `#137` set names *\"IOLTA reconciliation\"* among the *\"do or die\"* items; the weight follows his words, not the rule text",
      "Source": "**no cadence in the rule read** — TDRPC 1.15(a) (eff. 3/7/2025) states the record-keeping duty and no reconciliation cadence (and `reconcil` occurs nowhere else in the TDRPC text in that sense); the IOLTA and State Bar Rules are NOT HELD and may say otherwise",
      "Status": "PRACTICE",
      "Note": "the module must NEVER present it as a rule requirement",
    },
  },
  {
    key: "FOT-7",
    section: "7.3",
    cells: {
      "#": "`FOT-7`",
      "Template": "**IOLTA program — any annual certification or account notice the program requires**",
      "Kind / anchor": "`anniversary`, undated, **seeded INACTIVE**",
      "Lead": "—",
      "Weight": "hard",
      "Source": "Rules Governing the Operation of the Texas Access to Justice Foundation — **NOT HELD**",
      "Status": "NOT HELD",
      "Note": "nothing asserted about what the IOLTA rules require; dated when they are read",
    },
  },
  {
    key: "FOT-8",
    section: "7.4",
    cells: {
      "#": "`FOT-8`",
      "Template": "**Texas franchise tax annual report**",
      "Kind / anchor": "`fixed-annual` — **May 15** (the statute says *\"before May 16\"*); `conditionalPerPeriod`",
      "Lead": "45 d",
      "Weight": "hard",
      "Source": "Tex. Tax Code § 171.202(b); § 171.2022 (no report for a period in which no tax is due); § 171.002(d)(2) (no tax when total revenue ≤ $2.47 million or the § 171.006 figure); § 171.204(b) (the comptroller may not require an information report of such an entity)",
      "Status": "UNVERIFIED",
      "Conditional on": "whether the PLLC owes tax in the period — HIS FACT, per period",
    },
  },
  {
    key: "FOT-9",
    section: "7.4",
    cells: {
      "#": "`FOT-9`",
      "Template": "**Public Information Report** — owed *\"regardless of whether the entity is required to pay any tax\"*, *\"once a year\"*; the comptroller forwards it to the secretary of state; the comptroller holds a forfeiture power over a taxable entity's right to transact business (§ 171.2515(a), read — the GROUNDS are in § 171.251, NOT READ)",
      "Kind / anchor": "`fixed-annual` — the statute is silent on the date; **May 15 is the comptroller's form date in practice** (practitioner knowledge — NOT READ; the form's instructions / 34 TAC are outside every channel)",
      "Lead": "45 d",
      "Weight": "**hard** (Claude's call on the consequence class; his to settle)",
      "Source": "Tex. Tax Code § 171.203(a)–(c); § 171.2515(a)",
      "Status": "UNVERIFIED (statute); NOT READ (the date; the forfeiture grounds)",
      "Conditional on": "—",
    },
  },
  {
    key: "FOT-10",
    section: "7.4",
    cells: {
      "#": "`FOT-10`",
      "Template": "**Business personal property rendition** — tangible personal property used for the production of income and owned on January 1 (a law office's furniture, computers) is rendered to the chief appraiser *\"after January 1 and not later than April 15\"*; extension to May 15 on written request; a 10 percent penalty for a late rendition",
      "Kind / anchor": "`fixed-annual` — **April 15**",
      "Lead": "45 d",
      "Weight": "hard",
      "Source": "Tex. Tax Code §§ 22.01(a), 22.23(a)–(b), 22.28(a) — official corpus 2026-08-14",
      "Status": "UNVERIFIED",
      "Conditional on": "the firm owns income-producing tangible personal property on January 1 — HIS FACT",
    },
  },
  {
    key: "FOT-11",
    section: "7.4",
    cells: {
      "#": "`FOT-11`",
      "Template": "**Property tax payment on rendered property** — *\"due on receipt of the tax bill and … delinquent if not paid before February 1\"*",
      "Kind / anchor": "`fixed-annual` — January 31",
      "Lead": "30 d",
      "Weight": "hard",
      "Source": "Tex. Tax Code § 31.02(a)",
      "Status": "UNVERIFIED",
      "Conditional on": "a tax bill issued — HIS FACT",
    },
  },
  {
    key: "FOT-12",
    section: "7.4",
    cells: {
      "#": "`FOT-12`",
      "Template": "**Assumed-name certificate renewal** — an LLC files with the secretary of state only (§ 71.103(a); the county-clerk limbs were repealed 2019); a ≤ 10-year term, renewable within the six months before expiry *\"for any number of successive terms\"*",
      "Kind / anchor": "`anniversary` — the certificate's filing date, `everyYears: 10` (renewal window = the lead)",
      "Lead": "180 d",
      "Weight": "hard",
      "Source": "Tex. Bus. & Com. Code §§ 71.103(a), 71.151(a)–(c)",
      "Status": "UNVERIFIED",
      "Conditional on": "the firm holds an assumed-name certificate — HIS FACT",
    },
  },
  {
    key: "FOT-13",
    section: "7.5",
    cells: {
      "#": "`FOT-13`",
      "Template": "**Forms W-2 to employees and W-2/W-3 to SSA**",
      "Kind / anchor": "`fixed-annual` — **January 31**; `conditionalPerPeriod`",
      "Lead": "30 d",
      "Weight": "hard",
      "Source": "26 CFR 31.6051-1(d)(1)(i); 26 CFR 31.6071(a)-1(a)(3)(i) — eCFR pages through the fetch layer, request 2026-09-07, up_to_date_as_of 2026-09-03",
      "Status": "**TIER B**",
      "Conditional on": "wages paid in the year",
    },
  },
  {
    key: "FOT-14",
    section: "7.5",
    cells: {
      "#": "`FOT-14`",
      "Template": "**Form 941 quarterly**",
      "Kind / anchor": "`fixed-quarterly` — Apr 30 · Jul 31 · Oct 31 · Jan 31 (*the last day of the first calendar month following the period* — the fetch layer's wording; the dates are the module's arithmetic for calendar quarters); `conditionalPerPeriod`",
      "Lead": "14 d",
      "Weight": "hard",
      "Source": "26 CFR 31.6071(a)-1(a)(1) — eCFR page through the fetch layer, request 2026-09-07, up_to_date_as_of 2026-09-03",
      "Status": "**TIER B**",
      "Conditional on": "wages paid in the quarter",
    },
  },
  {
    key: "FOT-15",
    section: "7.5",
    cells: {
      "#": "`FOT-15`",
      "Template": "**Form 940 (FUTA) annual return**",
      "Kind / anchor": "`fixed-annual` — January 31 (the fetch layer summarized the FUTA paragraph as *due the last day of the first month*; the section itself was not read for it)",
      "Lead": "30 d",
      "Weight": "hard",
      "Source": "26 CFR 31.6071(a)-1 (the FUTA paragraph) — same fetch, same dates",
      "Status": "**TIER B (summary only)**",
      "Conditional on": "wages paid",
    },
  },
  {
    key: "FOT-16",
    section: "7.5",
    cells: {
      "#": "`FOT-16`",
      "Template": "**Texas Workforce Commission quarterly wage report and unemployment contribution**",
      "Kind / anchor": "`fixed-quarterly` — the quarter-end-plus-one-month dates in practice (NOT READ: the report deadline is in 40 TAC, outside every channel; Labor Code chs. 204 and 213 were extracted and searched for a quarterly-report date — the hits are the contribution scheme's quarter references, and no report deadline was found; not a full read)",
      "Lead": "14 d",
      "Weight": "hard",
      "Source": "Tex. Labor Code ch. 204 (contributions), ch. 213 (enforcement); 40 TAC § 815.106",
      "Status": "NOT READ (date)",
      "Conditional on": "wages paid",
    },
  },
  {
    key: "FOT-17",
    section: "7.5",
    cells: {
      "#": "`FOT-17`",
      "Template": "**Form 1099-NEC** (and other 1099s: Feb 28 / Mar 31 electronic)",
      "Kind / anchor": "`fixed-annual` — **January 31**; `conditionalPerPeriod`",
      "Lead": "30 d",
      "Weight": "hard",
      "Source": "26 CFR 1.6041-6 — same fetch, same dates",
      "Status": "**TIER B**",
      "Conditional on": "reportable nonemployee compensation paid in the year (experts, investigators, a contract paralegal) — HIS FACT, likely yes for a PI practice",
    },
  },
  {
    key: "FOT-18",
    section: "7.5",
    cells: {
      "#": "`FOT-18`",
      "Template": "**Federal income-tax return(s) and quarterly estimates**",
      "Kind / anchor": "`fixed-annual` / `fixed-quarterly` — **dates seeded from practitioner knowledge and marked NOT READ**: estimates Apr 15 · Jun 15 · Sep 15 · Jan 15; the entity return Mar 15 (S corporation / partnership) or Apr 15",
      "Lead": "30 d",
      "Weight": "hard",
      "Source": "26 U.S.C. §§ 6654(c)(2), 6072(a)–(b); 26 CFR 1.6072-1/-2 — the U.S. Code has an official online publisher (the Office of the Law Revision Counsel; govinfo.gov) that is NOT a named SOURCING channel — a channel question (`Q-FO-9`)",
      "Status": "NOT READ",
      "Conditional on": "entity election and estimated-tax posture — HIS FACT; his accountant's dates at activation",
    },
  },
  {
    key: "boi-note",
    section: "7.5",
    cells: {
      "#": "—",
      "Template": "**Beneficial-ownership (BOI) report**",
      "Kind / anchor": "**seeded INACTIVE with the note** — on the TIER B read a Texas PLLC is a domestic entity and exempt; the register remembers the question if the rule moves (an interim rule can be withdrawn)",
      "Lead": "—",
      "Weight": "—",
      "Source": "31 CFR 1010.380(c)(1)(ii), (c)(2)(xxiv) — eCFR page through the fetch layer, request 2026-09-07, up_to_date_as_of 2026-09-03",
      "Status": "**TIER B** — his read of the section decides",
      "Conditional on": "—",
    },
  },
  {
    key: "FOT-19",
    section: "7.6",
    cells: {
      "#": "`FOT-19`",
      "Template": "**Professional-liability (malpractice) policy renewal**",
      "Kind / anchor": "`anniversary` — the policy's renewal date",
      "Lead": "60 d",
      "Weight": "hard",
      "Source": "none (the policy)",
      "Status": "HIS FACT",
      "Conditional on": "—",
    },
  },
  {
    key: "FOT-20",
    section: "7.6",
    cells: {
      "#": "`FOT-20`",
      "Template": "**Other coverage renewals** (cyber, general liability, if held)",
      "Kind / anchor": "`anniversary`",
      "Lead": "60 d",
      "Weight": "hard",
      "Source": "none (the policy)",
      "Status": "HIS FACT",
      "Conditional on": "coverage held — HIS FACT",
    },
  },
  {
    key: "FOT-21",
    section: "7.6",
    cells: {
      "#": "`FOT-21`",
      "Template": "**Notary public commission renewal** (four-year term from qualification; a $10,000 bond at appointment)",
      "Kind / anchor": "`anniversary` — his qualification date, `everyYears: 4`",
      "Lead": "60 d",
      "Weight": "routine",
      "Source": "Tex. Gov't Code §§ 406.002, 406.010(a) — official corpus 2026-08-14",
      "Status": "UNVERIFIED",
      "Conditional on": "he holds a notary commission — HIS FACT",
    },
  },
  {
    key: "FOT-22",
    section: "7.7",
    cells: {
      "#": "`FOT-22`",
      "Template": "**Backup RESTORE TEST — documents** (pull a handful of files from the third copy and confirm they open; `#137`: *\"roughly 20 minutes quarterly at 7 GB\"*)",
      "Kind / anchor": "`interval-from-completion` — 91 days; **the first occurrence is due NOW** (`FOD-16`)",
      "Lead": "14 d",
      "Weight": "routine",
      "Status / note": "PRACTICE — `BR-3`'s origin case, the reason `FO-1` exists",
    },
  },
  {
    key: "FOT-23",
    section: "7.7",
    cells: {
      "#": "`FOT-23`",
      "Template": "**Database RESTORE TEST — the case data** (prove a Supabase backup actually restores)",
      "Kind / anchor": "`interval-from-completion` — 91 days; first due NOW",
      "Lead": "14 d",
      "Weight": "routine",
      "Status / note": "PRACTICE — `BR-3`'s sibling; the documents' third copy is not the database's",
    },
  },
  {
    key: "FOT-24",
    section: "7.7",
    cells: {
      "#": "`FOT-24`",
      "Template": "**Backup HEARTBEAT reviewed** — confirm the last successful copy is recent (`#137`: the heartbeat *\"shout[s] if that is more than a few days ago\"*; a human check until a monitor exists)",
      "Kind / anchor": "`fixed-monthly`; `collapse`",
      "Lead": "3 d",
      "Weight": "routine",
      "Status / note": "PRACTICE — carries `#137`'s hard requirement that monitoring applies to the VENDOR too",
    },
  },
  {
    key: "FOT-25",
    section: "7.7",
    cells: {
      "#": "`FOT-25`",
      "Template": "**Firm payment card expiry** — every auto-renewing subscription (Supabase Pro, Postmark, Microsoft 365, CloudLex) rides on it",
      "Kind / anchor": "`anniversary` — the card's expiry, `precision: month`",
      "Lead": "60 d",
      "Weight": "**hard**",
      "Status / note": "HIS FACT",
    },
  },
  {
    key: "FOT-26",
    section: "7.7",
    cells: {
      "#": "`FOT-26`",
      "Template": "**Annual closed-file and records review** — the practice proxy for the event-driven duties (trust records five years after termination; file retention/destruction; the website-vs-advertising-rule check)",
      "Kind / anchor": "`anniversary`",
      "Lead": "30 d",
      "Weight": "routine",
      "Status / note": "PRACTICE",
    },
  },
  {
    key: "FOT-27",
    section: "7.7",
    cells: {
      "#": "`FOT-27`",
      "Template": "**Domain renewal — `brennanstx.com`** (and any other domain the firm holds)",
      "Kind / anchor": "`anniversary` — HIS DATE",
      "Lead": "60 d",
      "Weight": "**hard**",
      "Status / note": "HIS FACT (the date) — the sign-in sender and the firm's mail ride on it",
    },
  },
  {
    key: "FOT-28",
    section: "7.7",
    cells: {
      "#": "`FOT-28`",
      "Template": "**Subscription renewals — Supabase Pro, Postmark, Microsoft 365, CloudLex** (one row each, or one row with a checklist)",
      "Kind / anchor": "`anniversary` — HIS DATE",
      "Lead": "30 d",
      "Weight": "routine (they bill automatically; the dated risk is `FOT-25`)",
      "Status / note": "HIS FACT (the dates) — Supabase Pro: gate 1 depends on it staying Pro; Postmark: gate 9's sender; the token's home is unchanged and never appears here",
    },
  },
  {
    key: "FOT-29",
    section: "7.7",
    cells: {
      "#": "`FOT-29`",
      "Template": "**Legal-research subscription — the auto-renewal NOTICE window** (the record names Lexis+ / Protégé)",
      "Kind / anchor": "`one-time` per term — HIS DATE",
      "Lead": "60 d",
      "Weight": "**hard**",
      "Status / note": "HIS FACT (the date) — the classic missed window; the contract governs",
    },
  },
  {
    key: "FOT-30",
    section: "7.7",
    cells: {
      "#": "`FOT-30`",
      "Template": "**Office lease — renewal or notice deadline**",
      "Kind / anchor": "`one-time` per term — HIS DATE",
      "Lead": "90 d",
      "Weight": "hard",
      "Status / note": "if leased — HIS FACT",
    },
  },
  {
    key: "FOT-31",
    section: "7.7",
    cells: {
      "#": "`FOT-31`",
      "Template": "**County / specialty bar memberships** (SABA, TCDLA, TTLA, sections — whatever he holds)",
      "Kind / anchor": "`anniversary` — HIS DATE",
      "Lead": "30 d",
      "Weight": "routine",
      "Status / note": "optional; register-only",
    },
  },
  {
    key: "FOT-32",
    section: "7.7",
    cells: {
      "#": "`FOT-32`",
      "Template": "**LegiScan API key rotation** (`M-4`: *\"Rotation after the T3 build is firm\"* — the LegiScan poller tier's `T3` build, not the transcription tier; `Q-WF-2` flags the two `T` series as ambiguous)",
      "Kind / anchor": "`one-time` — undated until that build lands",
      "Lead": "—",
      "Weight": "hard",
      "Status / note": "HIS FACT (the date); created inactive",
    },
  },
  {
    key: "FOT-33",
    section: "7.7",
    cells: {
      "#": "`FOT-33`",
      "Template": "**Model-call credential rotation** (the `H12-v` vendor credential, once a vendor is ruled)",
      "Kind / anchor": "`one-time` — undated",
      "Lead": "—",
      "Weight": "hard",
      "Status / note": "HIS FACT (the date, once a vendor is ruled) — created inactive; nothing about the credential's home is decided",
    },
  },
  {
    key: "FOT-34",
    section: "7.7",
    cells: {
      "#": "`FOT-34`",
      "Template": "**DMARC** (deferred past go-live, `#126`)",
      "Kind / anchor": "`one-time` — undated",
      "Lead": "—",
      "Weight": "routine",
      "Status / note": "PRACTICE — created inactive",
    },
  },
  {
    key: "FOT-35",
    section: "7.7",
    cells: {
      "#": "`FOT-35`",
      "Template": "**Security risk analysis** (HIPAA)",
      "Kind / anchor": "`anniversary` — annual by practice",
      "Lead": "30 d",
      "Weight": "routine",
      "Status / note": "45 CFR 164.308 returned 503 and was NOT READ; the regulation's own word is reported to be \"periodic\", not annual (practitioner knowledge); applicability is his call; no source text is claimed",
    },
  },
];

/** One row, by key. Throws rather than hand back undefined. */
export function catalogRow(key: FirmObligationCatalogKey): FirmObligationCatalogRow {
  const row = FIRM_OBLIGATION_CATALOG_ROWS.find((r) => r.key === key);
  if (!row) throw new Error(`firm-obligation catalog: no row ${key}`);
  return row;
}

/** One cell, by row key and column header. Throws when the row's table has no
 *  such column — a §7.7 row has no Source column, and a silent undefined there
 *  would render as an empty cite. */
export function catalogCell(key: FirmObligationCatalogKey, header: FirmObligationCatalogHeader): string {
  const row = catalogRow(key);
  const cell = row.cells[header];
  if (cell === undefined) {
    throw new Error(`firm-obligation catalog: ${key} (§${row.section}) has no "${header}" column`);
  }
  return cell;
}
