/**
 * THE FIXED SENTENCES — what the app PLACES, keyed by provider type.
 *
 * GENERATED BY `scripts/generate-form-text.mjs` — DO NOT EDIT BY HAND.
 * Every string below was sliced out of `docs/specs/form-engine.md` §9 by
 * program and written through unchanged. §9 carries a do-not-rewrite bar —
 * "approved by Michael verbatim" — so the build copies, it never rewords.
 * Correct the spec in the design space and re-run the generator; a drift test
 * re-reads the spec and fails the suite rather than letting a divergence reach
 * a served document.
 */

/**
 * `RC-1` (2026-08-31), in Michael's words: "The app puts the sentences in there
 * with the model writing the rest around them." These are those sentences.
 *
 * Two per treating type — the BASIS sentence (slot 2 of the paragraph) and the
 * CAUSATION sentence (slot 4, always last) — plus the mid-level rider's scope
 * sentence and §9.11 whole for the custodian-only shape. Each is a byte-exact
 * slice of `form-engine.md` §9, taken by the anchors the amendment slice §6.4
 * states, never by a sentence quoted into this file: a quoted copy is the thing
 * that would drift.
 *
 * AS-Q8a is why four types borrow §9.1's causation sentence rather than their
 * own: §9.5–§9.8's last sentence carries a future-care clause, and future care
 * belongs in the writer's middle instead.
 *
 * NOT here, by ruling: `pharmacy`, `mental-health`, `other-non-physician` and
 * `retained` place no fixed sentence at all.
 */

/** Which piece of a paragraph a fixed sentence is. */
export type FixedSentenceSlot = 'basis' | 'causation' | 'rider-scope' | 'custodian-only-whole';

export interface FixedSentence {
  /** Stored template key, `fixed:<slot>:<type>`. */
  key: string;
  slot: FixedSentenceSlot;
  /** The provider type whose paragraph places it. */
  providerType: string;
  /** The §9 section the text was sliced out of, e.g. "9.1". */
  sourceSection: string;
  /** The approved sentence, VERBATIM. */
  text: string;
}

export const FIXED_SENTENCES: FixedSentence[] = [
  {
    key: "fixed:basis:emergency-medicine",
    slot: "basis",
    providerType: "emergency-medicine",
    sourceSection: "9.1",
    text: "{provider_dr_name} will testify based on {provider_his_her} personal examination and treatment of {client}, {provider_his_her} review of {client}'s medical records, and {provider_his_her} medical knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:emergency-medicine",
    slot: "causation",
    providerType: "emergency-medicine",
    sourceSection: "9.1",
    text: "Plaintiff anticipates {provider_dr_name} will testify that the injuries treated were, within a reasonable degree of medical probability, caused by the incident of {incident_date}.",
  },
  {
    key: "fixed:basis:pain-management",
    slot: "basis",
    providerType: "pain-management",
    sourceSection: "9.5",
    text: "{provider_dr_name} will testify based on {provider_his_her} personal examination and treatment of {client}, {provider_his_her} review of {client}'s medical records and diagnostic imaging, and {provider_his_her} medical knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:pain-management",
    slot: "causation",
    providerType: "pain-management",
    sourceSection: "9.1",
    text: "Plaintiff anticipates {provider_dr_name} will testify that the injuries treated were, within a reasonable degree of medical probability, caused by the incident of {incident_date}.",
  },
  {
    key: "fixed:basis:orthopedic-surgery",
    slot: "basis",
    providerType: "orthopedic-surgery",
    sourceSection: "9.5",
    text: "{provider_dr_name} will testify based on {provider_his_her} personal examination and treatment of {client}, {provider_his_her} review of {client}'s medical records and diagnostic imaging, and {provider_his_her} medical knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:orthopedic-surgery",
    slot: "causation",
    providerType: "orthopedic-surgery",
    sourceSection: "9.1",
    text: "Plaintiff anticipates {provider_dr_name} will testify that the injuries treated were, within a reasonable degree of medical probability, caused by the incident of {incident_date}.",
  },
  {
    key: "fixed:basis:neurosurgery",
    slot: "basis",
    providerType: "neurosurgery",
    sourceSection: "9.5",
    text: "{provider_dr_name} will testify based on {provider_his_her} personal examination and treatment of {client}, {provider_his_her} review of {client}'s medical records and diagnostic imaging, and {provider_his_her} medical knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:neurosurgery",
    slot: "causation",
    providerType: "neurosurgery",
    sourceSection: "9.1",
    text: "Plaintiff anticipates {provider_dr_name} will testify that the injuries treated were, within a reasonable degree of medical probability, caused by the incident of {incident_date}.",
  },
  {
    key: "fixed:basis:primary-care",
    slot: "basis",
    providerType: "primary-care",
    sourceSection: "9.5",
    text: "{provider_dr_name} will testify based on {provider_his_her} personal examination and treatment of {client}, {provider_his_her} review of {client}'s medical records and diagnostic imaging, and {provider_his_her} medical knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:primary-care",
    slot: "causation",
    providerType: "primary-care",
    sourceSection: "9.1",
    text: "Plaintiff anticipates {provider_dr_name} will testify that the injuries treated were, within a reasonable degree of medical probability, caused by the incident of {incident_date}.",
  },
  {
    key: "fixed:basis:chiropractic",
    slot: "basis",
    providerType: "chiropractic",
    sourceSection: "9.4",
    text: "{provider_dr_name} will testify based on {provider_his_her} personal examination and treatment of {client}, {provider_his_her} review of {client}'s medical records and diagnostic imaging, and {provider_his_her} knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:chiropractic",
    slot: "causation",
    providerType: "chiropractic",
    sourceSection: "9.4",
    text: "Plaintiff anticipates {provider_dr_name} will testify that the injuries treated were, within a reasonable degree of medical probability, caused by the incident of {incident_date}.",
  },
  {
    key: "fixed:basis:physical-therapy",
    slot: "basis",
    providerType: "physical-therapy",
    sourceSection: "9.9",
    text: "{provider_dr_name} will testify based on {provider_his_her} personal evaluation and treatment of {client}, {provider_his_her} review of {client}'s medical records, and {provider_his_her} knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:physical-therapy",
    slot: "causation",
    providerType: "physical-therapy",
    sourceSection: "9.9",
    text: "Plaintiff anticipates {provider_dr_name} will testify that {client}'s functional limitations and impairments observed during treatment were consistent with the injuries {client_he_she} sustained in the incident of {incident_date}.",
  },
  {
    key: "fixed:basis:prehospital-ems",
    slot: "basis",
    providerType: "prehospital-ems",
    sourceSection: "9.3",
    text: "{provider_they} will testify based on {provider_their} personal examination and treatment of {client} at the scene and during transport, and {provider_their} medical knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:prehospital-ems",
    slot: "causation",
    providerType: "prehospital-ems",
    sourceSection: "9.3",
    text: "Plaintiff anticipates {provider_they} will testify that the condition and injuries for which {provider_they} provided emergency medical attention were consistent with the {incident_type} that occurred on {incident_date}.",
  },
  {
    key: "fixed:basis:radiologist",
    slot: "basis",
    providerType: "radiologist",
    sourceSection: "9.2",
    text: "{provider_dr_name} will testify based on {provider_his_her} review and interpretation of {client}'s diagnostic imaging, {provider_his_her} review of {client}'s medical records, and {provider_his_her} medical knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:radiologist",
    slot: "causation",
    providerType: "radiologist",
    sourceSection: "9.2",
    text: "Plaintiff anticipates {provider_dr_name} will testify that the findings shown in {client}'s imaging are, within a reasonable degree of medical probability, consistent with and caused by the incident of {incident_date}.",
  },
  {
    key: "fixed:basis:other-physician",
    slot: "basis",
    providerType: "other-physician",
    sourceSection: "9.1",
    text: "{provider_dr_name} will testify based on {provider_his_her} personal examination and treatment of {client}, {provider_his_her} review of {client}'s medical records, and {provider_his_her} medical knowledge gained from education, training, experience, and research.",
  },
  {
    key: "fixed:causation:other-physician",
    slot: "causation",
    providerType: "other-physician",
    sourceSection: "9.1",
    text: "Plaintiff anticipates {provider_dr_name} will testify that the injuries treated were, within a reasonable degree of medical probability, caused by the incident of {incident_date}.",
  },
  {
    key: "fixed:rider-scope:mid-level",
    slot: "rider-scope",
    providerType: "mid-level",
    sourceSection: "9.12",
    text: "{midlevel_short_name} will testify consistent with, and within the scope of, the testimony described above regarding {supervising_provider}, based on {midlevel_his_her} personal participation in {client}'s care.",
  },
  {
    key: "fixed:custodian-only-whole:custodian-only",
    slot: "custodian-only-whole",
    providerType: "custodian-only",
    sourceSection: "9.11",
    text: "The Custodian of Records for **{facility_name}** has knowledge of the medical records and billing records of {facility_name} pertaining to the care and treatment provided to {client} for the injuries {client_he_she} sustained in the {incident_type} on {incident_date}. The Custodian will testify that such records were made and kept in the regular course of business of {facility_name}, by persons with knowledge of the acts and events recorded, at or near the time of the acts and events recorded, and regarding the charges reflected in those records and the reasonableness of those charges.",
  },
];

export function fixedSentence(slot: FixedSentenceSlot, providerType: string): FixedSentence | undefined {
  return FIXED_SENTENCES.find((f) => f.slot === slot && f.providerType === providerType);
}

/**
 * The types this table holds a basis/causation pair for, in source-map order.
 *
 * NOT the same set as `FIXED_PAIR_TYPES` in `./providerTypes`, and the
 * difference is `radiologist`: it owns §9.2's pair but is not a TREATING_TYPE,
 * because an imaging facility is its own shape. `providerTypes` asserts the
 * relation between the two so neither drifts.
 */
export const FIXED_SENTENCE_TYPES = FIXED_SENTENCES
  .filter((f) => f.slot === 'basis')
  .map((f) => f.providerType);
