/**
 * `R8` UX-3 and UX-4 — WHAT CHANGED BETWEEN TWO TEMPLATE VERSIONS, MECHANICALLY.
 *
 * Michael walked the template editor by his own hand on 2026-09-05 and ruled
 * both halves of this:
 *
 *  - **UX-3, the surface: *"per row expander"*** — each version row gets a
 *    "what changed" expander showing the lines removed and the lines added
 *    against the IMMEDIATELY PRECEDING version. No compare-any-two; difficulty
 *    was confirmed low because every version stores its full body.
 *  - **UX-4, the note: *"If its going to do anything, I would like the changes
 *    made to be autogenerated instead of me having to explain what I just
 *    changed."* → *"mechanical, from the diff"*** — the Note column
 *    autogenerates from the diff, and the hand-note field stays, optional and
 *    unprompted.
 *
 * ⛔ **NO MODEL CALL, ANYWHERE IN THIS FILE.** A model-written change note was
 * NAMED at the sitting and EXCLUDED. No model path is wired at all until
 * `H12-v` is ruled and a BAA is signed, and a template body is not a thing this
 * build sends anywhere. Every sentence this file produces is counted or copied,
 * never written.
 *
 * `SD-15` names the note's format, PROVISIONAL, for Michael's eye.
 */

import { tokenNames } from './tokens';

export interface BodyDiff {
  removed: string[];
  added: string[];
  /** Tokens present in the old body and gone from the new one. */
  tokensRemoved: string[];
  /** Tokens present in the new body and absent from the old one. */
  tokensAdded: string[];
  /** 1-based indices of paragraphs that exist in both and read differently. */
  paragraphsEdited: number[];
}

const lines = (body: string) => body.split('\n');
const paragraphs = (body: string) =>
  body.split(/\n\s*\n/).map((p) => p.trim()).filter((p) => p !== '');

/**
 * A LINE-SET diff, deliberately, not a longest-common-subsequence one.
 *
 * "Lines removed / lines added" is what he asked to see, and a set difference
 * answers it exactly. An LCS diff would additionally claim to know which line
 * BECAME which — an inference about intent that this surface has no business
 * making, and one that reads plausibly while being wrong on a reordered
 * paragraph.
 *
 * Blank lines are ignored on both sides: they are formatting, and counting them
 * as changes would make every reflow look like an edit.
 */
export function diffBodies(previous: string, next: string): BodyDiff {
  const before = lines(previous).map((l) => l.trim()).filter((l) => l !== '');
  const after = lines(next).map((l) => l.trim()).filter((l) => l !== '');
  const beforeSet = new Set(before);
  const afterSet = new Set(after);

  const oldTokens = new Set(tokenNames(previous));
  const newTokens = new Set(tokenNames(next));

  const oldParas = paragraphs(previous);
  const newParas = paragraphs(next);
  const paragraphsEdited: number[] = [];
  for (let i = 0; i < Math.min(oldParas.length, newParas.length); i += 1) {
    if (oldParas[i] !== newParas[i]) paragraphsEdited.push(i + 1);
  }

  return {
    removed: before.filter((l) => !afterSet.has(l)),
    added: after.filter((l) => !beforeSet.has(l)),
    tokensRemoved: [...oldTokens].filter((t) => !newTokens.has(t)),
    tokensAdded: [...newTokens].filter((t) => !oldTokens.has(t)),
    paragraphsEdited,
  };
}

/**
 * `SD-15` — the autogenerated note.
 *
 * *"N lines changed · token {a} → {b} · ¶k edited"* — counts and token names
 * only, no prose about what the change MEANT. The token limb is emitted only
 * when exactly one token left and one arrived, which is the "renamed a token"
 * case the drawing shows; anything else is listed as removed and added rather
 * than described as a rename the diff cannot actually know happened.
 *
 * Returns the empty string when nothing changed, so a re-save with no edit
 * leaves the Note column empty rather than saying "0 lines changed".
 */
export function autoChangeNote(diff: BodyDiff): string {
  const parts: string[] = [];

  const changed = diff.removed.length + diff.added.length;
  if (changed > 0) parts.push(`${changed} line${changed === 1 ? '' : 's'} changed`);

  if (diff.tokensRemoved.length === 1 && diff.tokensAdded.length === 1) {
    parts.push(`token {${diff.tokensRemoved[0]}} → {${diff.tokensAdded[0]}}`);
  } else {
    if (diff.tokensRemoved.length > 0) {
      parts.push(`token${diff.tokensRemoved.length === 1 ? '' : 's'} removed: ${diff.tokensRemoved.map((t) => `{${t}}`).join(', ')}`);
    }
    if (diff.tokensAdded.length > 0) {
      parts.push(`token${diff.tokensAdded.length === 1 ? '' : 's'} added: ${diff.tokensAdded.map((t) => `{${t}}`).join(', ')}`);
    }
  }

  if (diff.paragraphsEdited.length > 0) {
    parts.push(`${diff.paragraphsEdited.map((n) => `¶${n}`).join(', ')} edited`);
  }

  return parts.join(' · ');
}

/**
 * `R8` UX-2 — tokens in a body that the seeded registry does not define.
 *
 * Michael: ***"Warn on save, dont block"***. The check is against the seeded
 * `FormTokenDefinition` registry, in the CANONICAL `{token}` form (FC-1), and
 * the caller saves anyway. Inline marking was offered and NOT taken.
 *
 * Today the editor checks only the legacy `{{…}}` convention, so an unknown
 * token surfaces for the first time at RENDER, as `unresolved`, in a document
 * that has already been produced.
 */
export function unknownTokens(body: string, known: Iterable<string>): string[] {
  const registry = new Set(known);
  return tokenNames(body).filter((t) => !registry.has(t));
}
