// FOS-2 B5 — the master .docx, tokenized at exactly its two headings.
//
// Authority: docs/specs/firm-obligations-fix-slice.md §3 item 16 and §7 item
// 13, as amended by Michael's ruling at the FOS-2 build's first stop,
// 2026-09-16: "Tokenize both headings". The static heading
// `PLAINTIFF’S 194.2(b) & 195.5 DISCLOSURES` sat twice in word/document.xml —
// paragraph 39 (counted from 0; under the caption) became `{instrument_title}`
// and paragraph 83 (over the responses, after the certificate of service)
// became `{footer_title}`. NEITHER is the footer: word/footer1.xml is not
// touched. The byte diff is EVIDENCE at
// docs/record/firm-obligations-fix-build-2026-09-16/master-docx-byte-diff-2026-09-16.md.
//
// The pre-edit master is not kept anywhere in the app, so it is RECONSTRUCTED
// here — the two tokens put back as the heading — and the reconstruction is
// proved to BE the pre-edit master by hashes captured before the edit. Without
// that proof, "the old skeleton" below would be the new one wearing a costume
// and every comparison against it would be circular.

import { describe, it, expect } from 'vitest';
// `?raw`, this repo's convention for reading source in a test (no node:fs).
import formsTab from '../../pages/FormsTab.tsx?raw';
import { readZip, writeZip, entryText, setEntryText, partsDiff, type ZipEntry } from '../zip';
import { paragraphTexts, replaceInXml } from '../docx';
import { parseTokens } from '../tokens';
import { renderInstrument, type RenderContext, type RenderResult } from '../renderer';
import { buildRenderContext } from '../context';
import { buildDesignations, blockItem } from '../generate';
import { FixtureParagraphWriter } from '../writer';
import { disclosuresSkeletonBytes } from '../skeletons/disclosuresSkeleton';
import { FIXTURE_BUNDLE, FIXTURE_ANSWERS, FIXTURE_PARTIES } from '../fixtures';
import type {
  CaseChronologyVersion, CaseProvider, CaseProviderIndividual,
} from '../../domain/caseProviders';

const DOC = 'word/document.xml';

/** The heading as it sat in the XML (U+2019; the ampersand escaped). */
const HEADING_XML = 'PLAINTIFF\u2019S 194.2(b) &amp; 195.5 DISCLOSURES';
/** The heading as text — what a one-client case resolves both tokens to. */
const HEADING_TEXT = 'PLAINTIFF\u2019S 194.2(b) & 195.5 DISCLOSURES';

/** sha256 of the PRE-EDIT word/document.xml, decompressed (94,056 bytes).
 *  Captured by FOS-2 lane B into C:\fos2\b5-baseline.json at HEAD f626f4d with
 *  the .docx clean, before any edit; re-verified at the same HEAD by the B5
 *  lane immediately before the edit, 2026-09-16. */
const PRE_SLICE_DOCUMENT_XML_SHA256 =
  'ebcf45d2a41528e774931fad98f3fd735863cf027401ceab49395d9f60b1712a';

/** sha256 of EVERY member of the pre-edit package, decompressed, in package
 *  order. Generated by program from `git show HEAD:` of the .docx at HEAD
 *  f626f4d (sha256 fefc4d07…, 16,937 bytes), 2026-09-16, before the edit. */
const PRE_SLICE_MEMBERS: [string, string][] = [
  ['word/', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'],
  ['word/_rels/', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'],
  ['word/_rels/document.xml.rels', '8e6401aa31ceadb1dea1bf102fe2b7c7110d8959734ed7b119caafc36a0bd1fd'],
  ['word/document.xml', 'ebcf45d2a41528e774931fad98f3fd735863cf027401ceab49395d9f60b1712a'],
  ['word/styles.xml', 'bdcc0ad40968665f717fea5d7f3b08ccbf2fcde8c95224ea31c7dcba5008fb98'],
  ['docProps/', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'],
  ['docProps/core.xml', '65a9ff8acd0bd610f6798c78278aecd0a9b9bf2f064c334b312f0a2f0e6d5f64'],
  ['word/numbering.xml', 'aae067c32dd80d876358a0cc5ecef7f7442662e3648c0ecd9f1888677ddb4a6e'],
  ['_rels/', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'],
  ['_rels/.rels', '641d22a23aa9eb550103a7a01471eaeda5e84c69413e6e03e7fd290b4811a756'],
  ['word/_rels/footer1.xml.rels', 'bf64631f0bc7bd46712fef822bcfb22e069fa5779e133980ca0c9d81f00efc09'],
  ['word/_rels/footer2.xml.rels', 'bf64631f0bc7bd46712fef822bcfb22e069fa5779e133980ca0c9d81f00efc09'],
  ['word/footer1.xml', '938adf7ded479c582d93232c331f5f6a2717a7731e1046f186f0beab0b3e4e45'],
  ['word/footer2.xml', 'fc8ce6a3378d8fdf08ed496ff7c7bea24fa4703f0b9b4577975715ca90cfa472'],
  ['[Content_Types].xml', '70b5413aede9c9356107988b2ed2de5008be1d476fcd13ecf9b23028bbc39b17'],
  ['docProps/custom.xml', '8ec73cc7ce297e42cc652a1d1884d4ffb18ffa0ba7a6502a36f8da90d1be61a1'],
  ['docProps/app.xml', '579eba9a8d602575736c3880cf5b529aabbadee0e8cc0e4df8573db0ceadbd4b'],
  ['word/footnotes.xml', '774ce254f01cde1079d43e81a0db30ac82b3b2bae875b07c4fe28403ba30b6a9'],
  ['word/_rels/footnotes.xml.rels', 'bf64631f0bc7bd46712fef822bcfb22e069fa5779e133980ca0c9d81f00efc09'],
  ['word/endnotes.xml', '52f6c33e62c233e0d9f9c41ec259ffd943ea9cdc413293d43e6ffb213682a5cf'],
  ['word/_rels/endnotes.xml.rels', 'bf64631f0bc7bd46712fef822bcfb22e069fa5779e133980ca0c9d81f00efc09'],
  ['word/settings.xml', '36b68f012adfd6d2f8faaebc8d101632d3529e9d9fd57d6ef92198841e96f09e'],
  ['word/comments.xml', 'dd2d62f68c6fd01fc4d7d44081587af54ea3e135b9486cc44fa3c62d087adfec'],
  ['word/_rels/comments.xml.rels', 'bf64631f0bc7bd46712fef822bcfb22e069fa5779e133980ca0c9d81f00efc09'],
  ['word/fontTable.xml', 'a746dbb577ec5d68983d659707c0750ca89d40b9d3316e31af331d5e1c736bad'],
  ['word/_rels/fontTable.xml.rels', 'bf64631f0bc7bd46712fef822bcfb22e069fa5779e133980ca0c9d81f00efc09'],
];

async function sha256(data: Uint8Array | string): Promise<string> {
  const bytes = typeof data === 'string' ? new TextEncoder().encode(data) : data;
  const buf = new Uint8Array(bytes.length);
  buf.set(bytes);
  const digest = await crypto.subtle.digest('SHA-256', buf);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

const count = (s: string, needle: string) => s.split(needle).length - 1;

/** The new master, and the pre-edit master reconstructed from it. */
async function packages(): Promise<{
  next: ZipEntry[]; old: ZipEntry[]; nextBytes: Uint8Array; oldBytes: Uint8Array;
  xml: string; oldXml: string;
}> {
  const nextBytes = disclosuresSkeletonBytes();
  const next = await readZip(nextBytes);
  const xml = entryText(next, DOC);
  const oldXml = replaceInXml(
    replaceInXml(xml, '>{instrument_title}</w:t>', `>${HEADING_XML}</w:t>`, { expect: 1 }),
    '>{footer_title}</w:t>', `>${HEADING_XML}</w:t>`, { expect: 1 },
  );
  const old = setEntryText(next, DOC, oldXml);
  return { next, old, nextBytes, oldBytes: await writeZip(old), xml, oldXml };
}

/** FormsTab's one-client value, READ FROM ITS SOURCE rather than retyped, so
 *  the generation below renders exactly what the page would put in the tokens. */
function formsTabStaticHeading(): string {
  const m = /const MASTER_STATIC_HEADING = '([^']*)';/.exec(formsTab);
  if (!m) throw new Error('MASTER_STATIC_HEADING not found in FormsTab.tsx');
  return JSON.parse(`"${m[1]}"`) as string;
}

describe('FOS-2 B5 — the master carries the two heading tokens and nothing else changed', () => {
  it('document.xml holds {instrument_title} once, {footer_title} once, and the static heading zero times', async () => {
    const { xml } = await packages();
    expect(count(xml, '{instrument_title}')).toBe(1);
    expect(count(xml, '{footer_title}')).toBe(1);
    expect(count(xml, HEADING_XML)).toBe(0);
    expect(count(xml, 'PLAINTIFF\u2019S 194.2(b)')).toBe(0);
    // Each token is the WHOLE text of its node, in the heading's own run.
    expect(count(xml, '<w:t xml:space="preserve">{instrument_title}</w:t>')).toBe(1);
    expect(count(xml, '<w:t xml:space="preserve">{footer_title}</w:t>')).toBe(1);
    // They are the ONLY single-brace tokens in the master; the rest stay legacy.
    const canonical = parseTokens(xml).filter((t) => t.convention === 'canonical');
    expect(canonical.map((t) => t.name)).toEqual(['instrument_title', 'footer_title']);
  });

  it('puts them where the ruling put them — paragraph 39 under the caption, 83 after the certificate of service', async () => {
    const { xml } = await packages();
    const paras = paragraphTexts(xml);
    expect(paras[39]).toBe('{instrument_title}');
    expect(paras[83]).toBe('{footer_title}');
    expect(paras[37]).toBe('{{county_name_caps}} COUNTY, TEXAS');
    const cos = paras.indexOf('CERTIFICATE OF SERVICE');
    expect(cos).toBeGreaterThan(39);
    expect(cos).toBeLessThan(83);
    expect(paras[85].startsWith('194.2(b)(1)')).toBe(true);
  });

  it('the reconstructed pre-edit document.xml IS the pre-edit member, byte for byte', async () => {
    const { oldXml } = await packages();
    const bytes = new TextEncoder().encode(oldXml);
    expect(bytes.length).toBe(94056);
    expect(await sha256(bytes)).toBe(PRE_SLICE_DOCUMENT_XML_SHA256);
    expect(count(oldXml, `>${HEADING_XML}</w:t>`)).toBe(2);
  });

  it('every member of the reconstructed package is the pre-edit member, and partsDiff(old, new) is exactly word/document.xml', async () => {
    const { next, old } = await packages();
    expect(PRE_SLICE_MEMBERS).toHaveLength(26);
    expect(old.map((e) => e.name)).toEqual(PRE_SLICE_MEMBERS.map(([name]) => name));
    for (const e of old) {
      const want = PRE_SLICE_MEMBERS.find(([name]) => name === e.name)![1];
      expect(await sha256(e.data), e.name).toBe(want);
    }
    expect(partsDiff(old, next)).toEqual([DOC]);
  });

  it('word/footer1.xml is untouched — the same decompressed bytes as the pre-edit member, and still static', async () => {
    const { next, old } = await packages();
    const before = old.find((e) => e.name === 'word/footer1.xml')!.data;
    const after = next.find((e) => e.name === 'word/footer1.xml')!.data;
    expect(Array.from(after)).toEqual(Array.from(before));
    expect(await sha256(after))
      .toBe(PRE_SLICE_MEMBERS.find(([name]) => name === 'word/footer1.xml')![1]);
    const text = entryText(next, 'word/footer1.xml');
    expect(text).toContain('PLAINTIFF\u2019S TRCP 194.2(B) AND 195.5 DISCLOSURES');
    expect(parseTokens(text)).toEqual([]);
  });
});

// ------------------------------------------------ the two scalars resolve

const T = '2026-09-16T00:00:00.000Z';
const ER_PARTY = FIXTURE_PARTIES.find((p) => p.id === 'fx-p-prov-er')!;
const PROVIDER: CaseProvider = {
  id: 'cp-b5', caseId: 'fx-case-1', facilityPartyId: ER_PARTY.id,
  providerType: 'emergency-medicine', lop: false, createdAt: T, updatedAt: T,
};
const INDIVIDUAL: CaseProviderIndividual = {
  id: 'i-b5', caseProviderId: 'cp-b5', displayName: 'Imani Calcite', credentialSuffix: 'M.D.',
  provenance: 'hand', missingFromLatest: false, handEditedFields: [], sortOrder: 1,
  createdAt: T, updatedAt: T,
};
const CHRONOLOGY: CaseChronologyVersion = {
  id: 'chv-b5', caseId: 'fx-case-1', versionNo: 1, droppedAt: T,
  sourceFilename: 'chronology.pdf', sourceFormat: 'pdf', readable: true, createdAt: T,
  extractedText: 'Halite Regional Hospital: emergency evaluation by Imani Calcite, M.D.',
};

/**
 * A generation down the FormsTab path — R17's block and narrative replace the
 * expert region — on a fixture with NO custodian-only shape and NO D-8 edge,
 * with the two heading tokens set to `heading`. Built ONCE and rendered against
 * both packages, so the only thing that differs between the two renders is the
 * skeleton.
 */
async function generationContext(heading: string): Promise<RenderContext> {
  const parties = { [ER_PARTY.id]: ER_PARTY };
  const out = await buildDesignations({
    writer: new FixtureParagraphWriter(),
    selected: [PROVIDER],
    individuals: [INDIVIDUAL],
    visits: [],
    chronologyVersions: [CHRONOLOGY],
    facilityParties: parties,
    clientName: 'Alba Quartzmoor',
    clientPronoun: 'she',
    incidentDateIso: '2025-03-14',
    caseType: 'Motor vehicle collision',
    writerInstructions: '',
  });
  expect(out.paragraphs.map((p) => p.shape)).toEqual(['treating-single']);
  expect(out.paragraphs.some((p) => p.shape === 'custodian-only')).toBe(false);

  const { context } = buildRenderContext(FIXTURE_BUNDLE, FIXTURE_ANSWERS);
  context.regions.testifying_expert = out.blocks.map((b) => blockItem(b, parties));
  context.itemSelects = { ...context.itemSelects, 'testifying_expert:0': 'treating_provider' };
  context.itemNarratives = out.itemNarratives;
  context.scalars = { ...context.scalars, instrument_title: heading, footer_title: heading };
  return context;
}

async function documentXml(r: RenderResult): Promise<string> {
  return entryText(await readZip(r.docx), DOC);
}

describe('FOS-2 B5 — a ONE-client instrument serves exactly what the pre-edit master served', () => {
  it('FormsTab resolves both tokens to the master\'s static heading on one client, and to the title on many', () => {
    expect(formsTabStaticHeading()).toBe(HEADING_TEXT);
    expect(formsTab).toContain('const heading = multiClient ? title : MASTER_STATIC_HEADING;');
    expect(formsTab).toContain('instrument_title: heading,');
    expect(formsTab).toContain('footer_title: heading,');
    // The record, the filename and the on-screen label still read `title`.
    expect(formsTab).toMatch(/ {8}title,\r?\n {8}content: rendered\.plainText,/);
    expect(formsTab).toContain('{instrumentTitle(');
    // The old note that called the second heading "the footer" is corrected.
    expect(formsTab).not.toContain('present twice (title and footer)');
    expect(formsTab).not.toContain('these resolve nothing yet');
  });

  it('renders document.xml text IDENTICAL to the reconstructed pre-edit master, and the whole .docx byte-identical', async () => {
    const { nextBytes, oldBytes } = await packages();
    const context = await generationContext(formsTabStaticHeading());

    const before = await renderInstrument(oldBytes, context);
    const after = await renderInstrument(nextBytes, context);

    expect(await documentXml(after)).toBe(await documentXml(before));
    expect(after.plainText).toBe(before.plainText);
    expect(Array.from(after.docx)).toEqual(Array.from(before.docx));
    expect(after.changedParts).toEqual([DOC]);

    // And it is the heading that is served, twice, with nothing left unresolved.
    expect(count(after.plainText, HEADING_TEXT)).toBe(2);
    expect(after.plainText).toContain('HALITE REGIONAL HOSPITAL');
    expect(after.lint.unresolvedTokens).toEqual([]);
  });

  it('the renderer fixture (one client) lints clean on the tokenized master', async () => {
    const { context } = buildRenderContext(FIXTURE_BUNDLE, FIXTURE_ANSWERS);
    expect(context.scalars.instrument_title).toBe(HEADING_TEXT);
    expect(context.scalars.footer_title).toBe(HEADING_TEXT);
    const { oldBytes } = await packages();
    const before = await renderInstrument(oldBytes, context);
    const after = await renderInstrument(disclosuresSkeletonBytes(), context);
    expect(Array.from(after.docx)).toEqual(Array.from(before.docx));
    expect(after.lint.unresolvedTokens).toEqual([]);
  });
});

describe('FOS-2 B5 — a MULTI-client instrument\'s two headings carry the ruled R15 title', () => {
  // `instrumentTitle` in FormsTab, original posture, responding plaintiff named.
  const R15 = "Plaintiff Alba Quartzmoor's TRCP 194.2(b) and 195.5 Disclosures";

  it('is the title FormsTab builds', () => {
    expect(formsTab).toContain("const owner = who === '' ? \"Plaintiff's\" : `Plaintiff ${who}'s`;");
    expect(formsTab).toContain('return `${owner} TRCP 194.2(b) and 195.5 Disclosures`;');
  });

  it('serves the title at both heading spots and the static heading nowhere', async () => {
    const context = await generationContext(R15);
    const rendered = await renderInstrument(disclosuresSkeletonBytes(), context);
    const paras = paragraphTexts(await documentXml(rendered)).map((p) => p.trim());

    const at = paras.flatMap((p, i) => (p === R15 ? [i] : []));
    expect(at).toHaveLength(2);
    const county = paras.findIndex((p) => p.endsWith('COUNTY, TEXAS'));
    const cos = paras.indexOf('CERTIFICATE OF SERVICE');
    expect(county).toBeGreaterThan(-1);
    expect(at[0]).toBeGreaterThan(county);
    expect(at[0]).toBeLessThan(cos);
    expect(at[1]).toBeGreaterThan(cos);

    expect(rendered.plainText).not.toContain(HEADING_TEXT);
    expect(rendered.lint.unresolvedTokens).toEqual([]);
  });
});
