import type { CaseRecord, PartyRecord, CasePartyLink } from '../domain/types';
import type { CalendarEvent } from '../domain/calendar';
import type {
  MedicalBill, BillLineItem, CodeMapping, EOBRecord, AnalysisRun, AnalysisResultLine,
  ReviewLogEntry, LegalRule, FeeSchedule, FeeScheduleRate, GeneratedDocument,
  ProviderBillingProfile,
} from '../domain/billing';

/**
 * Data-access interface. Two implementations:
 *  - LocalAdapter: browser localStorage, seeded demo data — zero setup, default.
 *  - SupabaseAdapter: the real central database (set VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY).
 * The UI only ever talks to this interface, so switching backends is a config change.
 */
export interface DataAdapter {
  listCases(): Promise<CaseRecord[]>;
  getCase(id: string): Promise<CaseRecord | null>;
  /** Bulk fetch — avoids per-row round-trips when resolving link tables. */
  getCases(ids: string[]): Promise<CaseRecord[]>;
  createCase(data: Omit<CaseRecord, 'id' | 'fileNumber' | 'createdAt' | 'updatedAt'>): Promise<CaseRecord>;
  updateCase(id: string, patch: Partial<CaseRecord>): Promise<CaseRecord>;

  listParties(): Promise<PartyRecord[]>;
  getParty(id: string): Promise<PartyRecord | null>;
  /** Bulk fetch — avoids per-row round-trips when resolving link tables. */
  getParties(ids: string[]): Promise<PartyRecord[]>;
  createParty(data: Omit<PartyRecord, 'id' | 'createdAt' | 'updatedAt'>): Promise<PartyRecord>;
  /** Only displayName and fields are mutable — party type/kind are frozen at creation. */
  updateParty(id: string, patch: Partial<Pick<PartyRecord, 'displayName' | 'fields'>>): Promise<PartyRecord>;

  listLinksForCase(caseId: string): Promise<CasePartyLink[]>;
  listLinksForParty(partyId: string): Promise<CasePartyLink[]>;
  createLink(data: Omit<CasePartyLink, 'id' | 'createdAt'>): Promise<CasePartyLink>;
  deleteLink(id: string): Promise<void>;

  // ---- Billing module (Phase 1a) ----
  listBillsForCase(caseId: string): Promise<MedicalBill[]>;
  getBill(id: string): Promise<MedicalBill | null>;
  createBill(data: Omit<MedicalBill, 'id' | 'createdAt' | 'updatedAt'>): Promise<MedicalBill>;
  updateBill(id: string, patch: Partial<MedicalBill>): Promise<MedicalBill>;
  /** Cascades to line items, EOB, and analysis runs/result lines for the bill. */
  deleteBill(id: string): Promise<void>;

  listLineItems(billId: string): Promise<BillLineItem[]>;
  createLineItem(data: Omit<BillLineItem, 'id'>): Promise<BillLineItem>;
  updateLineItem(id: string, patch: Partial<BillLineItem>): Promise<BillLineItem>;
  deleteLineItem(id: string): Promise<void>;

  /** Chargemaster memory — protective-order mappings are excluded from cross-case use by callers. */
  listCodeMappings(): Promise<CodeMapping[]>;
  createCodeMapping(data: Omit<CodeMapping, 'id'>): Promise<CodeMapping>;

  /** All bills attached to a provider-business party, across cases — feeds the billing profile. */
  listBillsForProvider(providerPartyId: string): Promise<MedicalBill[]>;
  getProviderProfile(providerPartyId: string): Promise<ProviderBillingProfile | null>;
  /** Full replace keyed on providerPartyId — the profile is a computed projection, never hand-edited. */
  upsertProviderProfile(data: Omit<ProviderBillingProfile, 'id' | 'updatedAt'>): Promise<ProviderBillingProfile>;

  getEobForBill(billId: string): Promise<EOBRecord | null>;
  saveEob(billId: string, data: Omit<EOBRecord, 'id' | 'billId' | 'updatedAt'>): Promise<EOBRecord>;

  listRunsForCase(caseId: string): Promise<AnalysisRun[]>;
  listRunsForBill(billId: string): Promise<AnalysisRun[]>;
  /** Persists a computed run + its result lines (ids pre-generated by the analysis engine). */
  createRun(run: AnalysisRun, resultLines: AnalysisResultLine[]): Promise<AnalysisRun>;
  /** Attorney sign-off: provisional → confirmed. Only confirmed runs may feed downstream math. */
  confirmRun(id: string, reviewer: string): Promise<AnalysisRun>;
  listResultLines(runId: string): Promise<AnalysisResultLine[]>;

  appendReviewLog(entry: Omit<ReviewLogEntry, 'id' | 'timestamp'>): Promise<ReviewLogEntry>;
  listReviewLog(entityType: string, entityId: string): Promise<ReviewLogEntry[]>;

  listLegalRules(): Promise<LegalRule[]>;
  /** Bumps version on every edit. Verified status is an attorney action in the UI —
   *  nothing programmatic ever sets it. */
  updateLegalRule(id: string, patch: Partial<Omit<LegalRule, 'id' | 'version' | 'createdAt' | 'updatedAt'>>): Promise<LegalRule>;

  listFeeSchedules(): Promise<FeeSchedule[]>;
  listRates(scheduleIds: string[]): Promise<FeeScheduleRate[]>;
  createFeeSchedule(
    data: Omit<FeeSchedule, 'id' | 'createdAt'>,
    rates: Omit<FeeScheduleRate, 'id' | 'scheduleId'>[],
  ): Promise<FeeSchedule>;
  deleteFeeSchedule(id: string): Promise<void>;

  listDocumentsForCase(caseId: string): Promise<GeneratedDocument[]>;
  createDocument(data: Omit<GeneratedDocument, 'id' | 'generatedAt'>): Promise<GeneratedDocument>;

  // ---- Calendar (Outlook push Phase 1) ----
  listEventsForCase(caseId: string): Promise<CalendarEvent[]>;
  /** The retry queue: everything not yet reflected in Outlook (pending or error), across cases. */
  listEventsPendingSync(): Promise<CalendarEvent[]>;
  createEvent(data: Omit<CalendarEvent, 'id' | 'createdAt' | 'updatedAt'>): Promise<CalendarEvent>;
  updateEvent(id: string, patch: Partial<CalendarEvent>): Promise<CalendarEvent>;
}
