import type { CaseRecord, PartyRecord, CasePartyLink } from '../domain/types';
import type { CalendarEvent } from '../domain/calendar';
import type {
  Transcript, TranscriptParticipant, StagingItem, RoutingDecision,
  GlossaryTerm, TagTemplate,
} from '../domain/transcripts';
import type { Charge, OaaIntakeRecord } from '../domain/oaa';
import type {
  MedicalBill, BillLineItem, CodeMapping, EOBRecord, AnalysisRun, AnalysisResultLine,
  ReviewLogEntry, LegalRule, FeeSchedule, FeeScheduleRate, GeneratedDocument,
  ProviderBillingProfile,
} from '../domain/billing';

/**
 * Data-access interface. Two implementations:
 *  - LocalAdapter: browser localStorage, seeded demo data — zero setup, default.
 *  - SupabaseAdapter: the real central database (set VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY).
 * The UI only ever talks to this interface, so switching backends is a config change.
 */
export interface DataAdapter {
  listCases(): Promise<CaseRecord[]>;
  getCase(id: string): Promise<CaseRecord | null>;
  /** Bulk fetch — avoids per-row round-trips when resolving link tables. */
  getCases(ids: string[]): Promise<CaseRecord[]>;
  createCase(data: Omit<CaseRecord, 'id' | 'fileNumber' | 'createdAt' | 'updatedAt'>): Promise<CaseRecord>;
  updateCase(id: string, patch: Partial<CaseRecord>): Promise<CaseRecord>;

  listParties(): Promise<PartyRecord[]>;
  getParty(id: string): Promise<PartyRecord | null>;
  /** Bulk fetch — avoids per-row round-trips when resolving link tables. */
  getParties(ids: string[]): Promise<PartyRecord[]>;
  createParty(data: Omit<PartyRecord, 'id' | 'createdAt' | 'updatedAt'>): Promise<PartyRecord>;
  /** Only displayName and fields are mutable — party type/kind are frozen at creation. */
  updateParty(id: string, patch: Partial<Pick<PartyRecord, 'displayName' | 'fields'>>): Promise<PartyRecord>;

  listLinksForCase(caseId: string): Promise<CasePartyLink[]>;
  listLinksForParty(partyId: string): Promise<CasePartyLink[]>;
  createLink(data: Omit<CasePartyLink, 'id' | 'createdAt'>): Promise<CasePartyLink>;
  deleteLink(id: string): Promise<void>;

  // ---- Billing module (Phase 1a) ----
  listBillsForCase(caseId: string): Promise<MedicalBill[]>;
  getBill(id: string): Promise<MedicalBill | null>;
  createBill(data: Omit<MedicalBill, 'id' | 'createdAt' | 'updatedAt'>): Promise<MedicalBill>;
  updateBill(id: string, patch: Partial<MedicalBill>): Promise<MedicalBill>;
  /** Cascades to line items, EOB, and analysis runs/result lines for the bill. */
  deleteBill(id: string): Promise<void>;

  listLineItems(billId: string): Promise<BillLineItem[]>;
  createLineItem(data: Omit<BillLineItem, 'id'>): Promise<BillLineItem>;
  updateLineItem(id: string, patch: Partial<BillLineItem>): Promise<BillLineItem>;
  deleteLineItem(id: string): Promise<void>;

  /** Chargemaster memory — protective-order mappings are excluded from cross-case use by callers. */
  listCodeMappings(): Promise<CodeMapping[]>;
  createCodeMapping(data: Omit<CodeMapping, 'id'>): Promise<CodeMapping>;

  /** All bills attached to a provider-business party, across cases — feeds the billing profile. */
  listBillsForProvider(providerPartyId: string): Promise<MedicalBill[]>;
  getProviderProfile(providerPartyId: string): Promise<ProviderBillingProfile | null>;
  /** Full replace keyed on providerPartyId — the profile is a computed projection, never hand-edited. */
  upsertProviderProfile(data: Omit<ProviderBillingProfile, 'id' | 'updatedAt'>): Promise<ProviderBillingProfile>;

  getEobForBill(billId: string): Promise<EOBRecord | null>;
  saveEob(billId: string, data: Omit<EOBRecord, 'id' | 'billId' | 'updatedAt'>): Promise<EOBRecord>;

  listRunsForCase(caseId: string): Promise<AnalysisRun[]>;
  listRunsForBill(billId: string): Promise<AnalysisRun[]>;
  /** Persists a computed run + its result lines (ids pre-generated by the analysis engine). */
  createRun(run: AnalysisRun, resultLines: AnalysisResultLine[]): Promise<AnalysisRun>;
  /** Attorney sign-off: provisional → confirmed. Only confirmed runs may feed downstream math. */
  confirmRun(id: string, reviewer: string): Promise<AnalysisRun>;
  listResultLines(runId: string): Promise<AnalysisResultLine[]>;

  appendReviewLog(entry: Omit<ReviewLogEntry, 'id' | 'timestamp'>): Promise<ReviewLogEntry>;
  listReviewLog(entityType: string, entityId: string): Promise<ReviewLogEntry[]>;

  listLegalRules(): Promise<LegalRule[]>;
  /** Bumps version on every edit. Verified status is an attorney action in the UI —
   *  nothing programmatic ever sets it. */
  updateLegalRule(id: string, patch: Partial<Omit<LegalRule, 'id' | 'version' | 'createdAt' | 'updatedAt'>>): Promise<LegalRule>;

  listFeeSchedules(): Promise<FeeSchedule[]>;
  listRates(scheduleIds: string[]): Promise<FeeScheduleRate[]>;
  createFeeSchedule(
    data: Omit<FeeSchedule, 'id' | 'createdAt'>,
    rates: Omit<FeeScheduleRate, 'id' | 'scheduleId'>[],
  ): Promise<FeeSchedule>;
  deleteFeeSchedule(id: string): Promise<void>;

  listDocumentsForCase(caseId: string): Promise<GeneratedDocument[]>;
  createDocument(data: Omit<GeneratedDocument, 'id' | 'generatedAt'>): Promise<GeneratedDocument>;

  // ---- Calendar (Outlook push Phase 1) ----
  listEventsForCase(caseId: string): Promise<CalendarEvent[]>;
  /** The retry queue: everything not yet reflected in Outlook (pending or error), across cases. */
  listEventsPendingSync(): Promise<CalendarEvent[]>;
  createEvent(data: Omit<CalendarEvent, 'id' | 'createdAt' | 'updatedAt'>): Promise<CalendarEvent>;
  updateEvent(id: string, patch: Partial<CalendarEvent>): Promise<CalendarEvent>;

  // ---- Transcript sort & route (T1, transcript-sort-and-route-design.md) ----
  listTranscriptsForCase(caseId: string): Promise<Transcript[]>;
  /** The Office notes store — not-case-related recordings, kept and searchable (O3). */
  listOfficeNotes(): Promise<Transcript[]>;
  getTranscript(id: string): Promise<Transcript | null>;
  createTranscript(data: Omit<Transcript, 'id' | 'createdAt' | 'updatedAt'>): Promise<Transcript>;
  /** The verified flag is attorney-only in the UI — nothing programmatic sets it. */
  updateTranscript(id: string, patch: Partial<Transcript>): Promise<Transcript>;

  listParticipants(transcriptId: string): Promise<TranscriptParticipant[]>;
  /** Full replace of a transcript's speaker→party mapping. */
  saveParticipants(
    transcriptId: string,
    participants: Omit<TranscriptParticipant, 'id' | 'transcriptId'>[],
  ): Promise<TranscriptParticipant[]>;

  /** The staging inbox — attorney-only until the multi-user phase. */
  listStagingItems(): Promise<StagingItem[]>;
  getStagingItem(id: string): Promise<StagingItem | null>;
  createStagingItem(data: Omit<StagingItem, 'id' | 'createdAt'>): Promise<StagingItem>;
  updateStagingItem(id: string, patch: Partial<StagingItem>): Promise<StagingItem>;

  /** The tuning log: suggested vs. chosen on every routing decision (design §5). */
  appendRoutingDecision(data: Omit<RoutingDecision, 'id' | 'decidedAt'>): Promise<RoutingDecision>;
  listRoutingDecisions(): Promise<RoutingDecision[]>;

  /** Spoken-tag templates are rows, not code — Michael extends them in the UI. */
  listTagTemplates(): Promise<TagTemplate[]>;
  createTagTemplate(data: Omit<TagTemplate, 'id'>): Promise<TagTemplate>;
  deleteTagTemplate(id: string): Promise<void>;

  /** Firm/case glossary terms feeding the vocabulary boost lists (design D3). */
  listGlossaryTerms(): Promise<GlossaryTerm[]>;
  createGlossaryTerm(data: Omit<GlossaryTerm, 'id'>): Promise<GlossaryTerm>;
  deleteGlossaryTerm(id: string): Promise<void>;

  // ---- OAA criminal intake (criminal-appointment-intake spec §1) ----
  listChargesForCase(caseId: string): Promise<Charge[]>;
  /** All charges across cases — feeds the duplicate-cause check at intake. */
  listCharges(): Promise<Charge[]>;
  createCharge(data: Omit<Charge, 'id' | 'createdAt' | 'updatedAt'>): Promise<Charge>;
  updateCharge(id: string, patch: Partial<Charge>): Promise<Charge>;
  deleteCharge(id: string): Promise<void>;

  /** Audit record of what an OAA intake extracted (template, text, provenance). */
  createOaaIntake(data: Omit<OaaIntakeRecord, 'id' | 'createdAt'>): Promise<OaaIntakeRecord>;
  getOaaIntakeForCase(caseId: string): Promise<OaaIntakeRecord | null>;
}
